fix: added github token input

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,6 +22,9 @@ inputs:
     description: "CLI version. Defaults to latest"
     default: "latest"
     required: false
+  token:
+    description: "GitHub token used to push tags"
+    required: true
 
 outputs:
   output:
@@ -77,6 +80,8 @@ runs:
 
         set +e
         OUTPUT=$(docker run --rm \
+            -e GITHUB_TOKEN="${{ inputs.token }}" \
+            -e GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
             -v "$GITHUB_WORKSPACE":/repo \
             -w /repo \
             ghcr.io/arnoldvann/monotrack:${{ inputs.version }} \
@@ -84,14 +89,14 @@ runs:
             --base "$BASE" \
             --head "$HEAD" \
             --config "${{ inputs.config }}")
-        EXIT_CODE=$?
-        set -e
 
-        if [ $EXIT_CODE -ne 0 ]; then
-            echo "::error::Monotrack command failed with exit code $EXIT_CODE"
+        if [ $? -gt 0 ]; then
+            echo "::error::Monotrack command failed with exit code $?"
             echo "$OUTPUT"
             exit $EXIT_CODE
         fi
+
+        set -e
 
         echo "Monotrack result: "
         echo "$OUTPUT"
